name: InnerEye
channels:
  - defaults
  - pytorch
dependencies:
  - pip=20.0.2
  - python=3.7.3
  - pytorch=1.3.0
  - pip:
      - git+https://github.com/analysiscenter/radio.git@6d53e25#egg=radio
      - git+https://github.com/ptrblck/apex.git@4ad9b3b#egg=apex
      - azureml-mlflow==1.11.0
      - azureml-sdk==1.11.0
      - azureml-tensorboard==1.11.0
      - blobxfer==1.9.4
      - dataclasses-json==0.5.2
      - flake8==3.8.3
      - gputil==1.4.0
      - h5py==2.10.0
      - joblib==0.16.0
      - matplotlib==3.1.0
      - mlflow==1.8.0
      - mypy==0.770
      - mypy-extensions==0.4.3
      - numpy==1.19.1
      - pandas==1.1.0
      - papermill==2.1.2
      - param==1.9.3
      - pillow==7.1.2
      - psutil==5.7.0
      - PyYAML==5.3.1
      - pyflakes==2.2.0
      - pytest==6.0.1
      - pytest-cov==2.10.1
      - pytest-forked==1.3.0
      - pytest-xdist==1.34.0
      - rich==3.0.5
      - rpdb==0.1.6
      - scikit-image==0.15.0
      - scikit-learn==0.23.2
      - scipy==1.3.1
      - seaborn==0.9.0
      - simpleitk==1.2.4
      - six==1.12.0
      - stopit==1.1.2
      - tabulate==0.8.7
      - tensorboardX==2.1
      - torchprof==1.1.1
      - torchvision==0.4.1
